//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTracking.PLMLogsEngine {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PSE_TrackingListInfo", Namespace="http://schemas.datacontract.org/2004/07/PSELogsBusinessEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PruebaTracking.PLMLogsEngine.PSE_TrackingParentInfo))]
    public partial class PSE_TrackingListInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EditionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SearchDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SearchTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrackIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeString {
            get {
                return this.CodeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeStringField, value) != true)) {
                    this.CodeStringField = value;
                    this.RaisePropertyChanged("CodeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EditionId {
            get {
                return this.EditionIdField;
            }
            set {
                if ((this.EditionIdField.Equals(value) != true)) {
                    this.EditionIdField = value;
                    this.RaisePropertyChanged("EditionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonFormat {
            get {
                return this.JsonFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonFormatField, value) != true)) {
                    this.JsonFormatField = value;
                    this.RaisePropertyChanged("JsonFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Replicate {
            get {
                return this.ReplicateField;
            }
            set {
                if ((this.ReplicateField.Equals(value) != true)) {
                    this.ReplicateField = value;
                    this.RaisePropertyChanged("Replicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SearchDate {
            get {
                return this.SearchDateField;
            }
            set {
                if ((this.SearchDateField.Equals(value) != true)) {
                    this.SearchDateField = value;
                    this.RaisePropertyChanged("SearchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchParameters {
            get {
                return this.SearchParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchParametersField, value) != true)) {
                    this.SearchParametersField = value;
                    this.RaisePropertyChanged("SearchParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SearchTypeId {
            get {
                return this.SearchTypeIdField;
            }
            set {
                if ((this.SearchTypeIdField.Equals(value) != true)) {
                    this.SearchTypeIdField = value;
                    this.RaisePropertyChanged("SearchTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((this.SourceIdField.Equals(value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackId {
            get {
                return this.TrackIdField;
            }
            set {
                if ((this.TrackIdField.Equals(value) != true)) {
                    this.TrackIdField = value;
                    this.RaisePropertyChanged("TrackId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PSE_TrackingParentInfo", Namespace="http://schemas.datacontract.org/2004/07/PSELogsBusinessEntities")]
    [System.SerializableAttribute()]
    public partial class PSE_TrackingParentInfo : PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo> ChildrenTrackingInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo> ChildrenTrackingInfo {
            get {
                return this.ChildrenTrackingInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenTrackingInfoField, value) != true)) {
                    this.ChildrenTrackingInfoField = value;
                    this.RaisePropertyChanged("ChildrenTrackingInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Info_TrackingListInfo", Namespace="http://schemas.datacontract.org/2004/07/InfoLogsBusinessEntries")]
    [System.SerializableAttribute()]
    public partial class Info_TrackingListInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSONFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SearchDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SearchTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrackIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeString {
            get {
                return this.CodeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeStringField, value) != true)) {
                    this.CodeStringField = value;
                    this.RaisePropertyChanged("CodeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSONFormat {
            get {
                return this.JSONFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.JSONFormatField, value) != true)) {
                    this.JSONFormatField = value;
                    this.RaisePropertyChanged("JSONFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Replicate {
            get {
                return this.ReplicateField;
            }
            set {
                if ((this.ReplicateField.Equals(value) != true)) {
                    this.ReplicateField = value;
                    this.RaisePropertyChanged("Replicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SearchDate {
            get {
                return this.SearchDateField;
            }
            set {
                if ((this.SearchDateField.Equals(value) != true)) {
                    this.SearchDateField = value;
                    this.RaisePropertyChanged("SearchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchParameters {
            get {
                return this.SearchParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchParametersField, value) != true)) {
                    this.SearchParametersField = value;
                    this.RaisePropertyChanged("SearchParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SearchTypeId {
            get {
                return this.SearchTypeIdField;
            }
            set {
                if ((this.SearchTypeIdField.Equals(value) != true)) {
                    this.SearchTypeIdField = value;
                    this.RaisePropertyChanged("SearchTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((this.SourceIdField.Equals(value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackId {
            get {
                return this.TrackIdField;
            }
            set {
                if ((this.TrackIdField.Equals(value) != true)) {
                    this.TrackIdField = value;
                    this.RaisePropertyChanged("TrackId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingListInfo", Namespace="http://schemas.datacontract.org/2004/07/PLMLogsBusinessEntries")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PruebaTracking.PLMLogsEngine.TrackingParentInfo))]
    public partial class TrackingListInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeGroupKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SearchDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SearchTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrackIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeGroupKey {
            get {
                return this.AttributeGroupKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeGroupKeyField, value) != true)) {
                    this.AttributeGroupKeyField = value;
                    this.RaisePropertyChanged("AttributeGroupKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeString {
            get {
                return this.CodeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeStringField, value) != true)) {
                    this.CodeStringField = value;
                    this.RaisePropertyChanged("CodeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonFormat {
            get {
                return this.JsonFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonFormatField, value) != true)) {
                    this.JsonFormatField = value;
                    this.RaisePropertyChanged("JsonFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Replicate {
            get {
                return this.ReplicateField;
            }
            set {
                if ((this.ReplicateField.Equals(value) != true)) {
                    this.ReplicateField = value;
                    this.RaisePropertyChanged("Replicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SearchDate {
            get {
                return this.SearchDateField;
            }
            set {
                if ((this.SearchDateField.Equals(value) != true)) {
                    this.SearchDateField = value;
                    this.RaisePropertyChanged("SearchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchParameters {
            get {
                return this.SearchParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchParametersField, value) != true)) {
                    this.SearchParametersField = value;
                    this.RaisePropertyChanged("SearchParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SearchTypeId {
            get {
                return this.SearchTypeIdField;
            }
            set {
                if ((this.SearchTypeIdField.Equals(value) != true)) {
                    this.SearchTypeIdField = value;
                    this.RaisePropertyChanged("SearchTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((this.SourceIdField.Equals(value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackId {
            get {
                return this.TrackIdField;
            }
            set {
                if ((this.TrackIdField.Equals(value) != true)) {
                    this.TrackIdField = value;
                    this.RaisePropertyChanged("TrackId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingParentInfo", Namespace="http://schemas.datacontract.org/2004/07/PLMLogsBusinessEntries")]
    [System.SerializableAttribute()]
    public partial class TrackingParentInfo : PruebaTracking.PLMLogsEngine.TrackingListInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.TrackingListInfo> ChildrenTrackingInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.TrackingListInfo> ChildrenTrackingInfo {
            get {
                return this.ChildrenTrackingInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenTrackingInfoField, value) != true)) {
                    this.ChildrenTrackingInfoField = value;
                    this.RaisePropertyChanged("ChildrenTrackingInfo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PLMLogsEngine.IPLMLogs")]
    public interface IPLMLogs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/addLogActivity", ReplyAction="http://tempuri.org/IPLMLogs/addLogActivityResponse")]
        void addLogActivity(PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo track);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/logsAddActivities", ReplyAction="http://tempuri.org/IPLMLogs/logsAddActivitiesResponse")]
        System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo> logsAddActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo> trackList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/addLogParentActivity", ReplyAction="http://tempuri.org/IPLMLogs/addLogParentActivityResponse")]
        void addLogParentActivity(PruebaTracking.PLMLogsEngine.PSE_TrackingParentInfo parentTrack);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/logsAddParentActivities", ReplyAction="http://tempuri.org/IPLMLogs/logsAddParentActivitiesResponse")]
        void logsAddParentActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.PSE_TrackingParentInfo> parentTrackList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/addTrackingActivity", ReplyAction="http://tempuri.org/IPLMLogs/addTrackingActivityResponse")]
        void addTrackingActivity(PruebaTracking.PLMLogsEngine.Info_TrackingListInfo track);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/addTrackingActivities", ReplyAction="http://tempuri.org/IPLMLogs/addTrackingActivitiesResponse")]
        void addTrackingActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.Info_TrackingListInfo> trackList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/addPLMTrackingActivity", ReplyAction="http://tempuri.org/IPLMLogs/addPLMTrackingActivityResponse")]
        void addPLMTrackingActivity(PruebaTracking.PLMLogsEngine.TrackingListInfo track);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/addPLMTrackingActivities", ReplyAction="http://tempuri.org/IPLMLogs/addPLMTrackingActivitiesResponse")]
        void addPLMTrackingActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.TrackingListInfo> trackList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/addPLMTrackingParentActivity", ReplyAction="http://tempuri.org/IPLMLogs/addPLMTrackingParentActivityResponse")]
        void addPLMTrackingParentActivity(PruebaTracking.PLMLogsEngine.TrackingParentInfo parentTrack);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMLogs/addPLMTrackingParentActivities", ReplyAction="http://tempuri.org/IPLMLogs/addPLMTrackingParentActivitiesResponse")]
        void addPLMTrackingParentActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.TrackingParentInfo> parentTrackList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPLMLogsChannel : PruebaTracking.PLMLogsEngine.IPLMLogs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PLMLogsClient : System.ServiceModel.ClientBase<PruebaTracking.PLMLogsEngine.IPLMLogs>, PruebaTracking.PLMLogsEngine.IPLMLogs {
        
        public PLMLogsClient() {
        }
        
        public PLMLogsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PLMLogsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PLMLogsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PLMLogsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addLogActivity(PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo track) {
            base.Channel.addLogActivity(track);
        }
        
        public System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo> logsAddActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.PSE_TrackingListInfo> trackList) {
            return base.Channel.logsAddActivities(trackList);
        }
        
        public void addLogParentActivity(PruebaTracking.PLMLogsEngine.PSE_TrackingParentInfo parentTrack) {
            base.Channel.addLogParentActivity(parentTrack);
        }
        
        public void logsAddParentActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.PSE_TrackingParentInfo> parentTrackList) {
            base.Channel.logsAddParentActivities(parentTrackList);
        }
        
        public void addTrackingActivity(PruebaTracking.PLMLogsEngine.Info_TrackingListInfo track) {
            base.Channel.addTrackingActivity(track);
        }
        
        public void addTrackingActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.Info_TrackingListInfo> trackList) {
            base.Channel.addTrackingActivities(trackList);
        }
        
        public void addPLMTrackingActivity(PruebaTracking.PLMLogsEngine.TrackingListInfo track) {
            base.Channel.addPLMTrackingActivity(track);
        }
        
        public void addPLMTrackingActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.TrackingListInfo> trackList) {
            base.Channel.addPLMTrackingActivities(trackList);
        }
        
        public void addPLMTrackingParentActivity(PruebaTracking.PLMLogsEngine.TrackingParentInfo parentTrack) {
            base.Channel.addPLMTrackingParentActivity(parentTrack);
        }
        
        public void addPLMTrackingParentActivities(System.Collections.Generic.List<PruebaTracking.PLMLogsEngine.TrackingParentInfo> parentTrackList) {
            base.Channel.addPLMTrackingParentActivities(parentTrackList);
        }
    }
}
