//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_CIIB_UNAM.wsUNAM {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articulo", Namespace="http://schemas.datacontract.org/2004/07/Ciib")]
    [System.SerializableAttribute()]
    public partial class Articulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AfiliacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PmidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResumenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Afiliacion {
            get {
                return this.AfiliacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AfiliacionField, value) != true)) {
                    this.AfiliacionField = value;
                    this.RaisePropertyChanged("Afiliacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pmid {
            get {
                return this.PmidField;
            }
            set {
                if ((object.ReferenceEquals(this.PmidField, value) != true)) {
                    this.PmidField = value;
                    this.RaisePropertyChanged("Pmid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resumen {
            get {
                return this.ResumenField;
            }
            set {
                if ((object.ReferenceEquals(this.ResumenField, value) != true)) {
                    this.ResumenField = value;
                    this.RaisePropertyChanged("Resumen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Revista {
            get {
                return this.RevistaField;
            }
            set {
                if ((object.ReferenceEquals(this.RevistaField, value) != true)) {
                    this.RevistaField = value;
                    this.RaisePropertyChanged("Revista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUNAM.ICiibServicio")]
    public interface ICiibServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICiibServicio/getArticle", ReplyAction="http://tempuri.org/ICiibServicio/getArticleResponse")]
        System.Collections.Generic.List<WS_CIIB_UNAM.wsUNAM.Articulo> getArticle(string db, string substance, int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICiibServicioChannel : WS_CIIB_UNAM.wsUNAM.ICiibServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CiibServicioClient : System.ServiceModel.ClientBase<WS_CIIB_UNAM.wsUNAM.ICiibServicio>, WS_CIIB_UNAM.wsUNAM.ICiibServicio {
        
        public CiibServicioClient() {
        }
        
        public CiibServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CiibServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CiibServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CiibServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WS_CIIB_UNAM.wsUNAM.Articulo> getArticle(string db, string substance, int value) {
            return base.Channel.getArticle(db, substance, value);
        }
    }
}
